version: '3.9'
services:
  standardfile:
    restart: always
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./standardfile.yml:/etc/standardfile/standardfile.yml:z
      - ./db:/etc/standardfile/database:z # chown -R $(id -u standardfile):$(id -g standardfile) ./db
